version: "3.7"

services:
    browser:
        image: jlesage/firefox
        container_name: client
        restart: always
        volumes:
            - /dev/shm:/dev/shm
        ports:
            - "5800:5800"
        networks:
            - mitm
    website:
        image: aikain/simplehttpserver:0.1
        container_name: server
        restart: always
        volumes:
            - ./server_files:/var/www
        networks:
            - mitm
    the_mitm:
        privileged: true
        build: .
        container_name: the_mitm
        volumes:
            - ./mitm_files:/proxy_files
        sysctls:
            # Configs para a conexão entre client e server continuar funcionando
            - net.ipv4.ip_forward=1
            - net.ipv6.conf.all.forwarding=1
            - net.ipv4.conf.all.send_redirects=0
        networks:
            - mitm

networks:
    mitm:
